from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import re
import sys

from onecut.errors import OneCutError
from onecut.media import Source


LEGACY_CAPTION = re.compile(r"^(\d+):(\d{2}):(\d{2}(?:\.\d+)?)\s+(.+)$")
LOCAL_BULLET_LONG = re.compile(r"^-\s*(\d+):(\d{2}):(\d{2}(?:\.\d+)?)\s*(.*)$")
LOCAL_BULLET_SHORT = re.compile(r"^-\s*(\d+):(\d{2}(?:\.\d+)?)\s*(.*)$")


@dataclass(frozen=True)
class Caption:
    start: float
    end: float
    text: str


@dataclass(frozen=True)
class RenderCopy:
    title: str
    description: str
    captions: tuple[Caption, ...]


def parse_local_bullet(line: str) -> tuple[float, str] | None:
    match = LOCAL_BULLET_LONG.fullmatch(line)
    if match:
        hours, minutes, seconds, text = match.groups()
        return int(hours) * 3600 + int(minutes) * 60 + float(seconds), text.strip()
    match = LOCAL_BULLET_SHORT.fullmatch(line)
    if match:
        minutes, seconds, text = match.groups()
        return int(minutes) * 60 + float(seconds), text.strip()
    if line.startswith("-"):
        return 0.0, line[1:].strip()
    return None


def format_time(value: float, include_fraction: bool = False) -> str:
    value = max(0.0, value)
    hours = int(value // 3600)
    minutes = int((value % 3600) // 60)
    seconds = value % 60
    if include_fraction and abs(seconds - round(seconds)) > 0.0005:
        second_text = f"{seconds:06.3f}".rstrip("0").rstrip(".")
    else:
        rounded = int(round(seconds))
        if rounded == 60:
            value = round(value)
            hours = int(value // 3600)
            minutes = int((value % 3600) // 60)
            rounded = 0
        second_text = f"{rounded:02d}"
    if hours:
        return f"{hours}:{minutes:02d}:{second_text}"
    return f"{minutes:02d}:{second_text}"


def prepare_captions(
    path: Path,
    sources: tuple[Source, ...],
    *,
    preserve_from: Path | None = None,
) -> None:
    title = ""
    description = ""
    captions_by_clip: dict[str, list[tuple[float, str]]] = {}
    orphan_captions: list[tuple[str, float, str]] = []
    existing_path = preserve_from or path
    existing_lines = (
        existing_path.read_text(encoding="utf-8-sig").splitlines()
        if existing_path.is_file()
        else []
    )
    structured = any(line.strip().startswith("CLIP:") for line in existing_lines)
    current_clip: str | None = None
    legacy_captions: list[tuple[float, str]] = []

    for raw_line in existing_lines:
        line = raw_line.strip()
        if line.startswith("TITLE:"):
            title = line.removeprefix("TITLE:").strip()
        elif line.startswith("DESC:"):
            description = line.removeprefix("DESC:").strip()
        elif structured and line.startswith("CLIP:"):
            current_clip = line.removeprefix("CLIP:").strip()
            captions_by_clip.setdefault(current_clip, [])
        elif structured and current_clip and line.startswith("-"):
            parsed = parse_local_bullet(line)
            if parsed and parsed[1]:
                captions_by_clip[current_clip].append(parsed)
        elif not structured:
            match = LEGACY_CAPTION.fullmatch(line)
            if match:
                hours, minutes, seconds, text = match.groups()
                legacy_captions.append(
                    (int(hours) * 3600 + int(minutes) * 60 + float(seconds), text)
                )

    if legacy_captions:
        offset = 0.0
        boundaries: list[tuple[float, float, str]] = []
        for source in sources:
            end = offset + source.duration
            boundaries.append((offset, end, source.path.name))
            offset = end
        for absolute, text in legacy_captions:
            for index, (start, end, name) in enumerate(boundaries):
                if absolute < end or index == len(boundaries) - 1:
                    captions_by_clip.setdefault(name, []).append(
                        (max(0.0, absolute - start), text)
                    )
                    break

    source_names = {source.path.name for source in sources}
    for name, items in captions_by_clip.items():
        if name not in source_names:
            orphan_captions.extend((name, local_time, text) for local_time, text in items)

    output = [
        f"TITLE: {title}",
        f"DESC: {description}",
        "",
        "# Generated by onecut captions in the same order used by onecut.",
        "# Each bullet timestamp is relative to that raw clip, not the final video.",
        "# Format: - MM:SS Caption text   (HH:MM:SS also works)",
        "# Empty placeholder bullets are ignored. "
        "Re-running the command preserves filled bullets.",
    ]
    preserved_count = 0
    for source in sources:
        name = source.path.name
        audio_label = "audio" if source.has_audio else "silent"
        output.extend(
            [
                "",
                f"CLIP: {name}",
                f"# Duration: {format_time(source.duration, include_fraction=True)} | "
                f"{source.display_width}x{source.display_height} | "
                f"{float(source.fps):.3f} fps | {audio_label}",
            ]
        )
        for local_time, text in sorted(
            captions_by_clip.get(name, []), key=lambda item: item[0]
        ):
            output.append(f"- {format_time(local_time, include_fraction=True)} {text}")
            preserved_count += 1
        output.extend(["- 00:00 ", "- 00:00 ", "- 00:00 "])

    if orphan_captions:
        output.extend(["", "# Preserved captions whose clips are no longer present:"])
        for name, local_time, text in orphan_captions:
            output.append(f"# ORPHAN: {name} | {format_time(local_time, True)} | {text}")

    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text("\n".join(output) + "\n", encoding="utf-8")
    os.replace(temporary, path)
    print(
        f"Prepared {path.name}: {len(sources)} clips, "
        f"{preserved_count} filled captions preserved"
    )


def parse_captions(
    path: Path,
    sources: tuple[Source, ...],
    display_seconds: float,
) -> RenderCopy:
    title = ""
    description = ""
    captions: list[Caption] = []
    file_name = path.name
    source_sections: dict[str, tuple[float, float]] = {}
    source_offset = 0.0
    for source in sources:
        source_sections[source.path.name] = (source_offset, source.duration)
        source_offset += source.duration

    current_clip: str | None = None
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8-sig").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#") or line.startswith("QUALITY:"):
            continue
        if line.startswith("TITLE:"):
            title = line.removeprefix("TITLE:").strip()
            continue
        if line.startswith("DESC:"):
            description = line.removeprefix("DESC:").strip()
            continue
        if line.startswith("CLIP:"):
            clip_name = line.removeprefix("CLIP:").strip()
            if clip_name not in source_sections:
                raise OneCutError(
                    f"{file_name} line {line_number} references a clip that is not present: "
                    f"{clip_name!r}\nRun 'onecut captions' to refresh the file list."
                )
            current_clip = clip_name
            continue
        if line.startswith("-"):
            if current_clip is None:
                raise OneCutError(
                    f"{file_name} line {line_number} is a bullet outside a CLIP section."
                )
            if line == "-":
                continue
            match = LOCAL_BULLET_LONG.fullmatch(line)
            if match:
                hours, minutes, seconds, text = match.groups()
                if int(minutes) > 59 or float(seconds) >= 60:
                    raise OneCutError(
                        f"invalid clip timestamp on {file_name} line {line_number}."
                    )
                local_start = int(hours) * 3600 + int(minutes) * 60 + float(seconds)
            else:
                match = LOCAL_BULLET_SHORT.fullmatch(line)
                if match:
                    minutes, seconds, text = match.groups()
                    if float(seconds) >= 60:
                        raise OneCutError(
                            f"invalid clip timestamp on {file_name} line {line_number}."
                        )
                    local_start = int(minutes) * 60 + float(seconds)
                else:
                    text = line[1:].strip()
                    local_start = 0.0
            text = text.strip()
            if not text:
                continue
            offset, duration = source_sections[current_clip]
            if local_start >= duration:
                raise OneCutError(
                    f"{file_name} line {line_number} is at {local_start:.3f}s, "
                    f"past the end of {current_clip} ({duration:.3f}s)."
                )
            start = offset + local_start
            captions.append(Caption(start, start + display_seconds, text))
            continue

        match = LEGACY_CAPTION.fullmatch(line)
        if not match:
            raise OneCutError(
                f"invalid {file_name} line {line_number}: {raw_line!r}\n"
                "Expected a CLIP section bullet or: HH:MM:SS caption text"
            )
        hours, minutes, seconds, text = match.groups()
        if int(minutes) > 59 or float(seconds) >= 60:
            raise OneCutError(f"invalid timestamp on {file_name} line {line_number}.")
        start = int(hours) * 3600 + int(minutes) * 60 + float(seconds)
        captions.append(Caption(start, start + display_seconds, text))

    footage_duration = sum(source.duration for source in sources)
    for caption in captions:
        if caption.start >= footage_duration:
            print(
                f"WARNING: caption at {caption.start:.3f}s is beyond the "
                f"{footage_duration:.3f}s footage: {caption.text}",
                file=sys.stderr,
            )
    return RenderCopy(title, description, tuple(captions))
